### ISSUE TITLE
Problems installing shard

### ISSUE THREAD

**Issue by felipetesc** [faustinoaq/sentry-run#4]
Hello I 'm receiving the following error when I run **shards install** 
If remove your shard all works.
```
Failed git ls-tree -r --full-tree --name-only v1.0.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```
My shard.yml is as it follows: 
++++++++++++++++++++++++
```yml
development_dependencies:
  sentry:
    github: samueleaton/sentry
    version: ~> 0.3.0
  sentry-run:
    github: faustinoaq/sentry-run
```

My crystal --version .... : 
```bash
Crystal 0.26.0 [eeb53c506] (2018-08-09)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
Can u help me ? TY.

**Comment by Dogcatfee** [comment]
I also ran into this issue, which lead me to find this other Crystal related issue from 2016 [git command failed ...](https://github.com/crystal-lang/shards/issues/108) 

This is the shard.yaml that works for me:

```  yaml
development_dependencies:
  sentry:
    github: samueleaton/sentry
    branch: master
  sentry-run:
    github: faustinoaq/sentry-run
```

Crystal version:
```
Crystal 0.27.0 (2018-11-02)

LLVM: 6.0.1
Default target: x86_64-pc-linux-gnu
```

Still not sure why ```branch: master``` fixes this, but it does. 
This also appears to be more of a samueleaton/sentry issue, and less of an faustinoaq/sentry-run issue.
